### ISSUE TITLE
Add to MELPA

### ISSUE THREAD

**Issue by carldotac** [louabill/ado-mode#2]
After running into some sharp corners with ESS and Stata, I was pleasantly surprised to find that this package exists. Have you considered adding it to MELPA?
https://github.com/melpa/melpa
This would greatly help with discoverability while allowing users to update ado-mode with the rest of their packages. (Twitter disabled its RSS feeds a while ago, by the way.)

**Comment by louabill** [comment]
Hi Carl,

> On Jul 25, 2018, at 13:22, Carl Lieberman <notifications@github.com> wrote:
> 
> After running into some sharp corners with ESS and Stata, I was pleasantly surprised to find that this package exists. Have you considered adding it to MELPA?
> https://github.com/melpa/melpa

I've thought about MELPA, but I'll have to see how much work I need to make it compatible. (Some echo in my mind says that I have to do a bit because the package started so long ago and has just layercaked since then.)

> This would greatly help with discoverability while allowing users to update ado-mode with the rest of their packages. (Twitter disabled its RSS feeds a while ago, by the way.)

Jeez. I'm not sure I ever knew that Twitter had RSS feeds (which is embarrassing). I just thought of Twitter as a really easy way to run an RSS without having to set up anything! 

Thanks for nudging me on this. I'll look into it once I've moved my current mountain of work a bit.

Cheers,

Bill

**Comment by hliebert** [comment]
Thanks for providing this package! It would be really great if you could submit it to MELPA. Alternatively you could also submit a pull request to integrate it into ESS.

Cheers,

Helge

**Comment by louabill** [comment]
I've finally jumped through all the hoops and submitted `ado-mode` to MELPA. Now it's time to see how long before it is really MELPA-ready.
