### ISSUE TITLE
Indentation, syntax highlighting fail after escaped quotes

### ISSUE THREAD

**Issue by paulnov** [louabill/ado-mode#4]
The following lines do not indent or highlight correctly:

    replace `var' = regexs(1) if regexm(`var', `"(.*)\"$"')
      gen x = 1

`ado-mode` does not recognize the end of the string in the first line, and thinks `gen x = 1` is still part of the string. 

Indentation / highlight can be restored by adding a comment line below with the following content:

        /* fix indentation ")} */

Ideally, `ado-mode` would indent and highlight the first line correctly.

**Comment by louabill** [comment]
Hmm... This happens because I long ago had made `ado-mode` ignore `\` as the escape character. I've long forgotten the reason, though I suspect it was because Stata only uses `\` as escape in regexps and for escaping a `$` for a global macro.

I'll play around with `\`s for a bit, to see if I can jog my memory about why it was not an escape character.

As a totally unrelated thing: you should move over to using `ustregexm()` and its cousins. The regular expression parsing is far more standard and far better (and handles unicode properly).

**Comment by louabill** [comment]
I just submitted 1.16.1.2 to MELPA, so I'll wait to make any change until I can update the version number.

**Comment by louabill** [comment]
`\` has been reinstated as an escape character, which should fix the above. Will be in 1.16.1.3 when it is uploaded.
